#!/usr/bin/python3
import sys
from multiprocessing import Process
sys.path.insert(0,"/root/git_rep/dl/web_dl/")

from web_dl.conf import CONF
from web_dl import log_util
from web_dl.ConfigParse import ConfigParse
from web_dl.tasks import celery_task

# 配置日志，但好像work进程的日志还是没有打印在指定的文件中
cp = ConfigParse(CONF.server['server_conf_path'])
cf_defaults = cp.read_file().get("default")
log_util.server_setup(cf_defaults.get("celery_log_file"),'celery')

app = celery_task.celery

# 异步任务
def start_worker():
    app.worker_main(argv=['worker', '-l', 'info'])

# 定时任务
def start_beat():
    beat = app.Beat(loglevel='info')
    beat.run()

if __name__ == "__main__":
    worker_process = Process(target=start_worker)
    beat_process = Process(target=start_beat)
    worker_process.start()
    beat_process.start()
    worker_process.join()
    beat_process.join()