#!/usr/bin/python3
# -*- coding: utf-8 -*-
import os
import sys
# 获取当前文件的目录
current_dir = os.path.dirname(os.path.abspath(__file__))
top_dir = os.path.dirname(os.path.dirname(current_dir))
# 将工作目录更改为当前文件的目录
os.chdir(top_dir)
sys.path.insert(0,top_dir)
# import pdb; pdb.set_trace()
from web_dl.cmd.api import main


if __name__ == "__main__":
    sys.exit(main())
